apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: scdprojectnamespace
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 80
      targetPort: 5000
     
